"""
Multi-format export pipeline for generated CAD geometry.

cad_generator.py previously hardcoded exactly two output formats (STEP
via cq.exporters, STL via cq.exporters). This module generalizes that
into a real Tier-1 export matrix:

    step  - exact B-Rep solid, mechanical CAD interchange (SolidWorks,
            Fusion 360, CATIA), CNC milling/turning, injection molding.
            Uses cq.exporters (STEPControl_Writer under the hood).
    stl   - triangulated mesh, additive manufacturing (FDM/SLA/SLS) and
            the in-browser three.js preview. Uses cq.exporters.
    iges  - exact B-Rep solid, legacy mechanical interchange. cadquery's
            own exporters module (2.3.1) doesn't expose an IGES
            ExportType - only STEPControl_Writer is wired up - so this
            calls OCP's IGESControl_Writer directly. That's not a new
            dependency: OCP is the OCCT binding cadquery is already
            built on, so this uses the same kernel STEP export uses.
    dxf   - true multi-view orthographic drawing (front/top/side), each
            view built via OCCT's HLR (hidden-line-removal) algorithm,
            for laser/plasma/waterjet cutting and full technical
            drawings - not a placeholder, not a single cross-section.
    pdf   - 1:1 scale vector engineering drawing with the same
            front/top/side views, a title block, and per-view labels,
            for shop-floor printing and dimensional inspection.

Scope notes (read before assuming more than what's here):

  * DXF/PDF are a real multi-view orthographic projection: front, top,
    and right-side views, each generated via OCCT's HLRBRep_Algo hidden-
    line-removal algorithm (through OCP, the same OCCT binding cadquery
    itself is built on - no new dependency), which separates each view's
    edges into visible (solid line) and hidden (dashed line) sets. This
    replaced the old single-horizontal-section approach (`Workplane.
    section()` at Z=0), which only captured geometry that happened to
    intersect one cutting plane - a stepped shaft's diameter change
    along its axis, for example, was invisible to it. There is no
    `multi_view`/`view_mode` flag; this is simply what `export_dxf` and
    `export_pdf` do now, for every part.
  * Assemblies get a *multi-part* drawing on top of that: `export_all`
    accepts a `parts` list (see assembly.get_assembly_parts) and, when
    given one, lays out one full front/top/side block per sub-part
    (each individually labeled) instead of a single block for the
    merged compound. This is a separate axis from multi-view - a
    single-part export always uses multi-view; a multi-part export uses
    multi-view *per part*, stacked on one sheet.
  * DXF layers are VISIBLE / HIDDEN / LABELS / BORDER, one drawing-line
    classification that applies to any part geometry, replacing the old
    PIECE_OUTLINE / HOLES / CENTERLINES set derived from section-wire
    nesting (which doesn't generalize to HLR edges - HLR doesn't produce
    closed hole wires, it produces visible/hidden edge segments).
  * GLTF is intentionally not included in this delivery. cadquery 2.3.1
    doesn't support it natively and a correct implementation needs an
    extra mesh-conversion dependency (e.g. trimesh) that wasn't in
    scope to add, test, and pin without being able to verify the
    resulting glTF against a viewer in this environment. Flagging this
    explicitly rather than shipping an unverified stub.
  * This module was written and reviewed against the cadquery 2.3.1 /
    OCP API surface pinned in requirements.txt, but could not be
    executed against real OCCT geometry in the sandbox this was
    authored in (no network access to install cadquery's native
    dependencies). Run `pytest tests/test_exporters.py` in an
    environment with the project's actual dependencies installed
    (the existing Dockerfile/CI already has them) before shipping.
"""
from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path
from typing import Union

import cadquery as cq

from exceptions import GenerationError, UnsupportedFormatError
from logging_config import get_logger

logger = get_logger(__name__)

SUPPORTED_FORMATS = {"step", "stl", "iges", "dxf", "pdf"}

# Formats generated by default when a caller doesn't specify. Multi-format
# export is the default as of 2.2.1: every supported format is produced
# unless a caller opts into a narrower list via `formats: [...]`. (Prior
# behavior - STEP+STL only - is still available by passing
# `formats: ["step", "stl"]` explicitly.)
DEFAULT_FORMATS = ("step", "stl", "iges", "dxf", "pdf")

_EXTENSION_BY_FORMAT = {"step": "step", "stl": "stl", "iges": "igs", "dxf": "dxf", "pdf": "pdf"}

ShapeLike = Union[cq.Workplane, cq.Shape, "cq.Assembly"]


def _as_workplane(obj: ShapeLike) -> cq.Workplane:
    """Normalize a Workplane, bare Shape, or Assembly into a Workplane so
    every exporter below has one calling convention. Assemblies are
    flattened to their compound solid - fine for STL/IGES/DXF/PDF, which
    only care about final geometry, not part hierarchy. (STEP export for
    assemblies stays on Assembly.save() elsewhere, since that's what
    preserves named sub-parts in the STEP file - see cad_generator.py.)
    """
    if isinstance(obj, cq.Workplane):
        return obj
    if hasattr(obj, "toCompound"):  # cq.assembly.Assembly
        return cq.Workplane(obj=obj.toCompound())
    return cq.Workplane(obj=obj)  # bare cq.Shape


def validate_formats(formats: list[str]) -> list[str]:
    """Normalize + validate a requested format list. Raises GenerationError
    (400-mapped, see exceptions.py) on anything unrecognized, so a typo'd
    format name fails fast with a clear message instead of silently being
    dropped."""
    normalized = [f.strip().lower() for f in formats if f and f.strip()]
    unknown = sorted(set(normalized) - SUPPORTED_FORMATS)
    if unknown:
        raise UnsupportedFormatError(
            f"Unsupported export format(s): {unknown}. "
            f"Supported formats: {sorted(SUPPORTED_FORMATS)}."
        )
    # de-dupe, preserve first-seen order
    seen: set[str] = set()
    result = []
    for f in normalized:
        if f not in seen:
            seen.add(f)
            result.append(f)
    return result or list(DEFAULT_FORMATS)


# --------------------------------------------------------------------
# STEP / STL - thin wrappers around the exports cad_generator.py already
# did inline, moved here so every format lives behind one interface.
# --------------------------------------------------------------------

def export_step(obj: ShapeLike, path: Path) -> Path:
    cq.exporters.export(_as_workplane(obj), str(path), exportType="STEP")
    return path


def export_stl(obj: ShapeLike, path: Path, tolerance: float = 0.1, angular_tolerance: float = 0.1) -> Path:
    cq.exporters.export(
        _as_workplane(obj),
        str(path),
        exportType="STL",
        tolerance=tolerance,
        angularTolerance=angular_tolerance,
    )
    return path


# --------------------------------------------------------------------
# IGES - exact B-Rep, via OCP's IGESControl_Writer directly.
# --------------------------------------------------------------------

def export_iges(obj: ShapeLike, path: Path) -> Path:
    """Write an exact boundary-representation IGES file. Mirrors the
    standard OCCT STEPControl_Writer pattern cadquery already uses for
    STEP internally, just with IGESControl_Writer, and sets the IGES
    unit flag to millimeters to match every other export in this module
    (cadquery/CQ geometry is unitless-but-conventionally-mm; without
    this the reader on the other end may assume inches)."""
    from OCP.IGESControl import IGESControl_Controller, IGESControl_Writer
    from OCP.Interface import Interface_Static

    workplane = _as_workplane(obj)
    shape = workplane.val()
    occt_shape = shape.wrapped if hasattr(shape, "wrapped") else shape

    IGESControl_Controller.Init_s()
    Interface_Static.SetCVal_s("write.iges.unit", "MM")
    writer = IGESControl_Writer()
    writer.AddShape(occt_shape)
    writer.ComputeModel()

    path.parent.mkdir(parents=True, exist_ok=True)
    ok = writer.Write(str(path))
    if not ok:
        raise GenerationError(f"IGES export failed (OCP IGESControl_Writer.Write returned false) for {path}")
    return path


# --------------------------------------------------------------------
# Multi-view orthographic projection (front / top / side) - the shared
# geometry pipeline behind DXF and PDF export. Built on OCCT's HLRBRep
# hidden-line-removal algorithm via OCP: for a given viewing direction,
# it separates a solid's projected edges into visible (solid line) and
# hidden (dashed line) sets, which is the standard way to turn a 3D part
# into a real technical drawing rather than one flat cross-section.
# --------------------------------------------------------------------

@dataclass
class _View:
    """One projected view's geometry, already expressed in the view's own
    local 2D drawing coordinates (local-X, local-Y - see _VIEW_AXES)."""
    name: str
    label: str
    visible: list[list[tuple[float, float]]]
    hidden: list[list[tuple[float, float]]]
    u_min: float
    u_max: float
    v_min: float
    v_max: float

    @property
    def width(self) -> float:
        return self.u_max - self.u_min

    @property
    def height(self) -> float:
        return self.v_max - self.v_min


# view_name -> (looking_direction, local_horizontal_axis). Local vertical
# is looking_direction x horizontal_axis, so it isn't listed separately.
# Front and top are both defined with local-X = world +X, so a top view
# stacks directly above a front view with no extra horizontal
# registration needed. Front and side are both defined with local-Y =
# world +Z, so a side view sits directly beside a front view with no
# extra vertical registration needed. This is the standard trick that
# makes a 3-view layout line up automatically instead of needing each
# view manually re-aligned - see _layout_three_views.
_VIEW_AXES: dict[str, tuple["cq.Vector", "cq.Vector"]] = {
    "front": (cq.Vector(0, -1, 0), cq.Vector(1, 0, 0)),
    "top": (cq.Vector(0, 0, -1), cq.Vector(1, 0, 0)),
    "side": (cq.Vector(-1, 0, 0), cq.Vector(0, -1, 0)),
}

_VIEW_LABELS = {"front": "FRONT VIEW", "top": "TOP VIEW", "side": "RIGHT SIDE VIEW"}

# Orientation of each view's local axes was worked out algebraically
# against OCCT's HLRAlgo_Projector convention (gp_Ax2(origin, direction,
# x_dir), local-Y = direction x x_dir) rather than checked against a
# rendered drawing, since this sandbox has no network access to install
# cadquery's native OCCT dependencies (see the module docstring and
# tests/test_exporters.py). Visually confirm view orientation the first
# time this runs against real geometry.


def _edge_to_points(edge: "cq.Edge", curve_segments: int = 32) -> list[tuple[float, float]]:
    """Discretize one edge into 2D (x, y) points, dropping z. Valid both
    for the old section-plane use (z is constant, the cut height) and
    for HLR-projected edges (z is projection depth, unneeded once
    visible/hidden classification has already happened)."""
    if edge.geomType() == "LINE":
        pts = [edge.startPoint(), edge.endPoint()]
    else:
        ds = [i / (curve_segments - 1) for i in range(curve_segments)]
        pts = edge.positions(ds)
    return [(p.x, p.y) for p in pts]


def _hlr_edges(shape, direction: "cq.Vector", x_dir: "cq.Vector") -> tuple[list, list]:
    """Run OCCT's HLRBRep_Algo on `shape` for one viewing direction and
    return (visible_edges, hidden_edges) as lists of cq.Edge, in the
    view's local 2D frame - each edge's own X/Y already are the drawing
    coordinates (Z is projection depth)."""
    from OCP.HLRAlgo import HLRAlgo_Projector
    from OCP.HLRBRep import HLRBRep_Algo, HLRBRep_HLRToShape
    from OCP.gp import gp_Ax2, gp_Dir, gp_Pnt

    occt_shape = shape.wrapped if hasattr(shape, "wrapped") else shape

    ax2 = gp_Ax2(
        gp_Pnt(0, 0, 0),
        gp_Dir(direction.x, direction.y, direction.z),
        gp_Dir(x_dir.x, x_dir.y, x_dir.z),
    )
    algo = HLRBRep_Algo()
    algo.Add(occt_shape)
    algo.Projector(HLRAlgo_Projector(ax2))
    algo.Update()
    algo.Hide()

    to_shape = HLRBRep_HLRToShape(algo)

    def _collect(*compounds) -> list:
        out = []
        for comp in compounds:
            if comp is None or comp.IsNull():
                continue
            out.extend(cq.Shape.cast(comp).Edges())
        return out

    # VCompound/HCompound: visible/hidden sharp (C0) edges. Rg1Line*:
    # edges at smooth (tangent, G1) face joins, e.g. a fillet's silhouette
    # - without these a filleted edge's outline goes missing. OutLine*:
    # the true silhouette of a curved surface (e.g. a cylinder's apparent
    # edge), which only exists as an HLR construct, not a real model
    # edge. All three visible sets get one line style; same for hidden.
    visible = _collect(to_shape.VCompound(), to_shape.Rg1LineVCompound(), to_shape.OutLineVCompound())
    hidden = _collect(to_shape.HCompound(), to_shape.Rg1LineHCompound(), to_shape.OutLineHCompound())
    return visible, hidden


def _build_view(shape, name: str) -> _View:
    direction, x_dir = _VIEW_AXES[name]
    visible_edges, hidden_edges = _hlr_edges(shape, direction, x_dir)

    visible_polylines = [_edge_to_points(e) for e in visible_edges]
    hidden_polylines = [_edge_to_points(e) for e in hidden_edges]

    all_pts = [p for line in (visible_polylines + hidden_polylines) for p in line]
    if not all_pts:
        raise GenerationError(
            f"HLR projection produced no edges for the {name} view. "
            "The part may be empty or degenerate."
        )
    xs = [p[0] for p in all_pts]
    ys = [p[1] for p in all_pts]
    return _View(
        name=name,
        label=_VIEW_LABELS[name],
        visible=visible_polylines,
        hidden=hidden_polylines,
        u_min=min(xs),
        u_max=max(xs),
        v_min=min(ys),
        v_max=max(ys),
    )


def _build_three_views(workplane: "cq.Workplane") -> list[_View]:
    shape = workplane.val()
    return [_build_view(shape, name) for name in ("front", "top", "side")]


def _layout_three_views(views: list[_View], gap: float = 28.0) -> dict[str, tuple[float, float]]:
    """Return {view_name: (offset_x, offset_y)} to add to each view's raw
    local coordinates so front/top/side sit in the standard third-angle
    drafting arrangement: top view above the front view (shared X
    registration), right-side view beside the front view (shared Z
    registration), `gap` drawing units (mm) apart. Default bumped from
    the original 15mm to 28mm when dimensioning was added - each view
    now draws an overall-width dimension below it and an overall-height
    dimension to its left (_add_dimensions_dxf/_add_dimensions_pdf), and
    15mm wasn't reliably enough room for a dimension line + arrows +
    text to fit in the gap without touching the neighboring view.
    Estimated, not pixel-verified against a rendered drawing - see the
    module docstring's standing no-cadquery-install caveat."""
    by_name = {v.name: v for v in views}
    front, top, side = by_name["front"], by_name["top"], by_name["side"]

    offsets = {"front": (-front.u_min, -front.v_min)}

    front_top_edge_y = -front.v_min + front.height
    offsets["top"] = (-front.u_min, front_top_edge_y + gap - top.v_min)

    front_right_edge_x = -front.u_min + front.width
    offsets["side"] = (front_right_edge_x + gap - side.u_min, -front.v_min)

    return offsets


def _combined_bbox(
    views: list[_View],
    offsets: dict[str, tuple[float, float]],
    label_clearance: float = 6.0,
    left_clearance: float = 0.0,
) -> tuple[float, float, float, float]:
    """(min_x, max_x, min_y, max_y) across every view's geometry once
    placed, including room below each view for its label text and, when
    `label_clearance`/`left_clearance` are widened by the caller, the
    width/height DIMENSION lines that _add_dimensions_dxf/
    _add_dimensions_pdf draw below and to the left of each view - if
    this box doesn't account for that space, the title block (placed
    just below the returned box) ends up overlapping the dimension
    lines instead of sitting cleanly below everything, same failure
    mode as the "dimension leaders cut through the title block" defect
    flagged in the export QA pass this fix comes from."""
    xs: list[float] = []
    ys: list[float] = []
    for v in views:
        ox, oy = offsets[v.name]
        xs += [v.u_min + ox - left_clearance, v.u_max + ox]
        ys += [v.v_min + oy - label_clearance, v.v_max + oy]
    return min(xs), max(xs), min(ys), max(ys)


def _part_size_mm(views: list["_View"]) -> tuple[float, float, float]:
    """Real (X, Y, Z) size of the actual solid, derived from the HLR
    views themselves - NOT from any input parameter (plate_size,
    motor_size_mm, etc). Those describe what was *requested*; a
    template can auto-correct or reinterpret a parameter (e.g. the
    fillet-radius auto-correction, or motor_mount snapping motor_size_mm
    to the nearest NEMA face size) so what actually got built can differ
    from what was asked for. Reading the size back off the projected
    geometry is the only way the reported size can't silently diverge
    from the part - same principle as why the drawing itself is HLR-
    derived instead of hand-computed from parameters.

    front's local-X = world +X and local-Y(vertical) = world +Z; side's
    local-X = world +/-Y (see _VIEW_AXES) - so front.width is the X
    extent, side.width is the Y extent, and front.height (== side.height,
    barring a non-rectangular silhouette) is the Z extent.
    """
    by_name = {v.name: v for v in views}
    front, side = by_name["front"], by_name["side"]
    return (front.width, side.width, front.height)


def _detect_circles(view: "_View", tolerance_frac: float = 0.02) -> list[tuple[float, float, float]]:
    """Find hole-like closed loops in `view.visible` and measure their
    real radius from the actual projected points - NOT from
    hole_diameter_mm or any other input parameter. A polyline qualifies
    as a circle if it's closed and every point sits within
    `tolerance_frac` of the mean centroid-to-point distance (a true
    circle's points are all equidistant from its center; anything else -
    a rounded-corner outline, a slot - fails this check and is correctly
    left undimensioned rather than mislabeled as a hole).

    Returns a list of (center_x, center_y, radius) tuples, one per
    detected circular loop, in the view's local drawing coordinates
    (same frame as view.u_min/u_max/visible/hidden - caller must add the
    view's layout offset before drawing).
    """
    circles: list[tuple[float, float, float]] = []
    for line in view.visible:
        if len(line) < 8:
            continue
        x0, y0 = line[0]
        x1, y1 = line[-1]
        if abs(x0 - x1) > 1e-3 or abs(y0 - y1) > 1e-3:
            continue  # not closed
        pts = line[:-1]  # drop the duplicated closing point
        cx = sum(p[0] for p in pts) / len(pts)
        cy = sum(p[1] for p in pts) / len(pts)
        radii = [((p[0] - cx) ** 2 + (p[1] - cy) ** 2) ** 0.5 for p in pts]
        r_mean = sum(radii) / len(radii)
        if r_mean < 1e-6:
            continue
        max_dev = max(abs(r - r_mean) for r in radii)
        if max_dev / r_mean <= tolerance_frac:
            circles.append((cx, cy, r_mean))
    return circles


def _distinct_hole_callouts(circles: list[tuple[float, float, float]], group_tol: float = 0.05) -> list[tuple[float, float, float]]:
    """Collapse detected circles into one representative circle per
    distinct real diameter (grouped within `group_tol` mm of radius), so
    a plate with 4 identical corner holes gets one callout, not four -
    matching normal drafting convention of dimensioning one instance of
    a repeated feature."""
    groups: list[list[tuple[float, float, float]]] = []
    for c in sorted(circles, key=lambda c: c[2]):
        placed = False
        for g in groups:
            if abs(g[0][2] - c[2]) <= group_tol:
                g.append(c)
                placed = True
                break
        if not placed:
            groups.append([c])
    return [g[0] for g in groups]


def _build_part_block(obj: "ShapeLike") -> tuple[list[_View], dict[str, tuple[float, float]]]:
    workplane = _as_workplane(obj)
    views = _build_three_views(workplane)
    offsets = _layout_three_views(views)
    return views, offsets


def _stack_part_blocks(
    parts: list[tuple[str, "ShapeLike"]],
    block_gap: float = 40.0,
    label_clearance: float = 20.0,
    left_clearance: float = 14.0,
) -> list[tuple[str, list[_View], dict[str, tuple[float, float]], float]]:
    """Lay out one front/top/side block per part, stacked vertically down
    the page. Each part keeps its own internal `_layout_three_views`
    registration; this only adds a per-block Y shift so blocks don't
    overlap. Returns (part_label, views, offsets, y_shift) tuples - the
    y_shift is added on top of each view's own offset when drawing.

    label_clearance/left_clearance default to the same 20.0/14.0 every
    export_dxf/export_pdf caller passes to _combined_bbox for the actual
    sheet extent - this function's own internal _combined_bbox call has
    to match those, or the vertical space it reserves per block
    (block_height, below) under-counts the room each view's width
    dimension line actually needs (drawn ~16mm below the view - see
    _add_dimensions_dxf/_add_dimensions_pdf - vs. the 6.0 the old
    default-args call reserved for it), the same "reserved box doesn't
    match what's actually drawn" defect _combined_bbox's own docstring
    already warns about for the single-part case. Currently masked by
    the generous fixed block_gap=40.0 rather than visible as an actual
    overlap, but not something to leave to that margin alone."""
    blocks: list[tuple[str, list[_View], dict[str, tuple[float, float]], float]] = []
    cursor_y = 0.0
    for name, shape in parts:
        views, offsets = _build_part_block(shape)
        _, _, y_min, y_max = _combined_bbox(
            views, offsets, label_clearance=label_clearance, left_clearance=left_clearance
        )
        block_height = y_max - y_min
        y_shift = cursor_y - y_min
        blocks.append((name, views, offsets, y_shift))
        cursor_y += block_height + block_gap
    return blocks



# --------------------------------------------------------------------
# DXF - via ezdxf (full control over layers and line entities; cadquery's
# own DXF exporter doesn't expose per-edge visible/hidden classification).
# --------------------------------------------------------------------

def _dxf_layers(doc) -> None:
    doc.layers.add("VISIBLE", color=7)
    doc.layers.add("HIDDEN", color=8, linetype="DASHED" if "DASHED" in doc.linetypes else "CONTINUOUS")
    doc.layers.add("LABELS", color=7)
    doc.layers.add("BORDER", color=7)
    doc.layers.add("DIMENSIONS", color=1)


def _draw_view_dxf(msp, view: _View, offset: tuple[float, float]) -> None:
    ox, oy = offset
    for line in view.visible:
        pts = [(x + ox, y + oy) for x, y in line]
        if len(pts) >= 2:
            msp.add_lwpolyline(pts, dxfattribs={"layer": "VISIBLE"})
    for line in view.hidden:
        pts = [(x + ox, y + oy) for x, y in line]
        if len(pts) >= 2:
            msp.add_lwpolyline(pts, dxfattribs={"layer": "HIDDEN"})
    label_x = view.u_min + ox
    label_y = view.v_min + oy - 6
    msp.add_text(view.label, dxfattribs={"layer": "LABELS", "height": 3.0}).set_placement((label_x, label_y))


def _add_dimensions_dxf(msp, view: _View, offset: tuple[float, float]) -> None:
    """Real DXF DIMENSION entities (associative dimension blocks that any
    CAD package recognizes as dimensions, not just lines+text pretending
    to be one) for one view's overall width/height and any detected
    holes. Every value is read back from the view's actual HLR geometry
    - see _part_size_mm / _detect_circles's docstrings for why that's
    required rather than optional here."""
    ox, oy = offset
    override = {"dimtxt": 2.5, "dimasz": 2.0, "dimexe": 1.5, "dimexo": 1.0}

    msp.add_linear_dim(
        base=(view.u_min + ox, view.v_min + oy - 16),
        p1=(view.u_min + ox, view.v_min + oy),
        p2=(view.u_max + ox, view.v_min + oy),
        angle=0,
        dimstyle="EZDXF",
        override=override,
        dxfattribs={"layer": "DIMENSIONS"},
    ).render()

    msp.add_linear_dim(
        base=(view.u_min + ox - 10, view.v_min + oy),
        p1=(view.u_min + ox, view.v_min + oy),
        p2=(view.u_min + ox, view.v_max + oy),
        angle=90,
        dimstyle="EZDXF",
        override=override,
        dxfattribs={"layer": "DIMENSIONS"},
    ).render()

    for cx, cy, r in _distinct_hole_callouts(_detect_circles(view)):
        msp.add_diameter_dim(
            center=(cx + ox, cy + oy),
            radius=r,
            angle=45,
            dimstyle="EZDXF",
            override=override,
            dxfattribs={"layer": "DIMENSIONS"},
        ).render()


def _draw_title_block_dxf(
    msp, x0: float, y0: float, width: float, height: float,
    part_name: str, material: str | None, part_type: str | None,
    size_mm: tuple[float, float, float] | None = None,
) -> None:
    msp.add_lwpolyline(
        [(x0, y0), (x0 + width, y0), (x0 + width, y0 + height), (x0, y0 + height)],
        dxfattribs={"layer": "BORDER", "closed": True},
    )
    msp.add_line((x0, y0 + height / 2), (x0 + width, y0 + height / 2), dxfattribs={"layer": "BORDER"})
    msp.add_line((x0 + width * 0.33, y0), (x0 + width * 0.33, y0 + height), dxfattribs={"layer": "BORDER"})
    msp.add_line((x0 + width * 0.66, y0), (x0 + width * 0.66, y0 + height), dxfattribs={"layer": "BORDER"})

    msp.add_text(
        f"PART: {part_name.upper()}", dxfattribs={"layer": "LABELS", "height": 3.5}
    ).set_placement((x0 + 3, y0 + height - 8))
    msp.add_text(
        f"TYPE: {(part_type or 'n/a').upper()}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + 3, y0 + 3))
    # SIZE is the real (X, Y, Z) size of the solid itself, measured off
    # the HLR views (_part_size_mm) - NOT the drawing sheet's own layout
    # extent. Reporting sheet size here was the original bug: a plate's
    # title block claimed it was 257mm wide because that's how much
    # sheet space three tiled views + gaps took up, not because the
    # part was actually that big.
    size_text = f"SIZE: {size_mm[0]:.1f} x {size_mm[1]:.1f} x {size_mm[2]:.1f} mm" if size_mm else "SIZE: n/a"
    msp.add_text(
        size_text, dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + width * 0.33 + 3, y0 + height - 8))
    msp.add_text(
        f"MATERIAL: {material or 'n/a'}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + width * 0.33 + 3, y0 + 3))
    msp.add_text(
        f"DATE: {_dt.date.today().isoformat()}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + width * 0.66 + 3, y0 + height - 8))


def export_dxf(
    obj: ShapeLike,
    path: Path,
    part_name: str = "PART",
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> Path:
    """Multi-view orthographic DXF (front/top/side, HLR visible/hidden
    edges, title block). If `parts` is given (assembly sub-parts, see
    assembly.get_assembly_parts), draws one such block per part, stacked
    on one sheet, instead of a single block for `obj`."""
    import ezdxf

    doc = ezdxf.new("R2010")
    _dxf_layers(doc)
    msp = doc.modelspace()

    if parts:
        blocks = _stack_part_blocks(parts)
        for label, views, offsets, y_shift in blocks:
            for view in views:
                ox, oy = offsets[view.name]
                _draw_view_dxf(msp, view, (ox, oy + y_shift))
                _add_dimensions_dxf(msp, view, (ox, oy + y_shift))
            first = views[0]
            fx, fy = offsets["front"]
            msp.add_text(
                label.upper(), dxfattribs={"layer": "LABELS", "height": 4.0}
            ).set_placement((fx, fy + y_shift + first.height + 12))
        overall_x0 = overall_y0 = float("inf")
        overall_x1 = overall_y1 = float("-inf")
        for _, views, offsets, y_shift in blocks:
            x0, x1, y0, y1 = _combined_bbox(
                views, {n: (o[0], o[1] + y_shift) for n, o in offsets.items()},
                label_clearance=20.0, left_clearance=14.0,
            )
            overall_x0, overall_x1 = min(overall_x0, x0), max(overall_x1, x1)
            overall_y0, overall_y1 = min(overall_y0, y0), max(overall_y1, y1)
        size_mm = None  # sheet holds multiple distinct parts - no single (X,Y,Z) to report
    else:
        views = _build_three_views(_as_workplane(obj))
        offsets = _layout_three_views(views)
        for view in views:
            _draw_view_dxf(msp, view, offsets[view.name])
            _add_dimensions_dxf(msp, view, offsets[view.name])
        overall_x0, overall_x1, overall_y0, overall_y1 = _combined_bbox(
            views, offsets, label_clearance=20.0, left_clearance=14.0
        )
        size_mm = _part_size_mm(views)

    tb_height = 16.0
    tb_y0 = overall_y0 - tb_height - 10
    _draw_title_block_dxf(
        msp, overall_x0, tb_y0, overall_x1 - overall_x0, tb_height,
        part_name, material, part_type, size_mm,
    )

    doc.header["$INSUNITS"] = 4  # 4 = millimeters, matches every other export in this module
    path.parent.mkdir(parents=True, exist_ok=True)
    doc.saveas(str(path))
    return path


# --------------------------------------------------------------------
# Vector PDF - same multi-view / multi-part geometry as DXF, via
# reportlab, at true 1:1 scale with a title block.
# --------------------------------------------------------------------

_VISIBLE_LINE_WIDTH_MM = 0.35
_HIDDEN_LINE_WIDTH_MM = 0.2
_DIM_LINE_WIDTH_MM = 0.15


def _draw_open_polyline_pdf(c, points: list[tuple[float, float]], dashed: bool = False) -> None:
    if len(points) < 2:
        return
    # Sets its own line width explicitly every call rather than trusting
    # whatever the canvas was last left at - it used to rely on a single
    # c.setLineWidth(0.5) set once before the whole multi-view loop, but
    # _add_dimensions_pdf (called after every view, in that same loop)
    # sets its own thinner dimension-line width and never restores it, so
    # every view after the first silently inherited the wrong (dimension)
    # width instead of the visible/hidden width it was supposed to have.
    # The 0.35/0.2mm values themselves also replace the old raw 0.5/0.3
    # *points* (~0.18mm/0.11mm) - too thin to read as a normal-weight
    # line at 1:1 print scale, which is the "light ink" look this fixes.
    from reportlab.lib.units import mm
    c.setLineWidth((_HIDDEN_LINE_WIDTH_MM if dashed else _VISIBLE_LINE_WIDTH_MM) * mm)
    c.setDash([2, 2] if dashed else [])
    p = c.beginPath()
    p.moveTo(*points[0])
    for pt in points[1:]:
        p.lineTo(*pt)
    c.drawPath(p, stroke=1, fill=0)
    c.setDash([])


def _draw_arrowhead_pdf(c, tip: tuple[float, float], direction_deg: float, size: float = 5.0) -> None:
    """Filled arrowhead in PAGE (point) coordinates, tip at `tip`, pointing
    along `direction_deg`."""
    import math
    a1 = math.radians(direction_deg + 150)
    a2 = math.radians(direction_deg - 150)
    p1 = (tip[0] + size * math.cos(a1), tip[1] + size * math.sin(a1))
    p2 = (tip[0] + size * math.cos(a2), tip[1] + size * math.sin(a2))
    path = c.beginPath()
    path.moveTo(*tip)
    path.lineTo(*p1)
    path.lineTo(*p2)
    path.close()
    c.drawPath(path, stroke=0, fill=1)


def _draw_horizontal_dim_pdf(c, to_page, x0: float, x1: float, y_measured: float, y_dim: float, text: str) -> None:
    """Horizontal dimension: extension lines up/down from (x0,y_measured)
    and (x1,y_measured) to the dimension line at y_dim, then the
    dimension line itself with arrowheads and centered text - all
    arguments in the view's local mm coordinates (offset already
    applied by the caller), converted to page points via `to_page`."""
    p0 = to_page((x0, y_measured))
    p1 = to_page((x1, y_measured))
    d0 = to_page((x0, y_dim))
    d1 = to_page((x1, y_dim))
    from reportlab.lib.units import mm
    c.setLineWidth(_DIM_LINE_WIDTH_MM * mm)
    c.line(p0[0], p0[1], d0[0], d0[1] + (6 if y_dim > y_measured else -6))
    c.line(p1[0], p1[1], d1[0], d1[1] + (6 if y_dim > y_measured else -6))
    c.line(d0[0], d0[1], d1[0], d1[1])
    _draw_arrowhead_pdf(c, d0, 0.0 if x1 > x0 else 180.0)
    _draw_arrowhead_pdf(c, d1, 180.0 if x1 > x0 else 0.0)
    c.setFont("Helvetica", 7)
    c.drawCentredString((d0[0] + d1[0]) / 2, d0[1] + 2, text)


def _draw_vertical_dim_pdf(c, to_page, y0: float, y1: float, x_measured: float, x_dim: float, text: str) -> None:
    """Vertical counterpart to _draw_horizontal_dim_pdf."""
    p0 = to_page((x_measured, y0))
    p1 = to_page((x_measured, y1))
    d0 = to_page((x_dim, y0))
    d1 = to_page((x_dim, y1))
    from reportlab.lib.units import mm
    c.setLineWidth(_DIM_LINE_WIDTH_MM * mm)
    c.line(p0[0], p0[1], d0[0] + (6 if x_dim > x_measured else -6), d0[1])
    c.line(p1[0], p1[1], d1[0] + (6 if x_dim > x_measured else -6), d1[1])
    c.line(d0[0], d0[1], d1[0], d1[1])
    _draw_arrowhead_pdf(c, d0, 90.0 if y1 > y0 else 270.0)
    _draw_arrowhead_pdf(c, d1, 270.0 if y1 > y0 else 90.0)
    c.saveState()
    c.setFont("Helvetica", 7)
    c.translate((d0[0] + d1[0]) / 2, (d0[1] + d1[1]) / 2)
    c.rotate(90)
    c.drawCentredString(0, 2, text)
    c.restoreState()


def _draw_diameter_leader_pdf(c, to_page, cx: float, cy: float, r: float, text: str) -> None:
    """Leader line from a 45-degree point on the hole's actual measured
    edge out to a diameter callout - standard drafting convention for
    dimensioning a circular hole."""
    import math
    edge_local = (cx + r * math.cos(math.radians(45)), cy + r * math.sin(math.radians(45)))
    label_local = (cx + (r + 8) * math.cos(math.radians(45)), cy + (r + 8) * math.sin(math.radians(45)))
    edge_pt = to_page(edge_local)
    label_pt = to_page(label_local)
    from reportlab.lib.units import mm
    c.setLineWidth(_DIM_LINE_WIDTH_MM * mm)
    c.line(edge_pt[0], edge_pt[1], label_pt[0], label_pt[1])
    c.setFont("Helvetica", 7)
    c.drawString(label_pt[0] + 2, label_pt[1] - 2, text)


def _add_dimensions_pdf(c, view: _View, offset: tuple[float, float], to_page) -> None:
    """Real dimensions for one view: overall width (below), overall
    height (left), and one diameter callout per distinct hole size
    actually measured in the geometry (see _detect_circles /
    _distinct_hole_callouts - never from hole_diameter_mm or any other
    input parameter, for the same reason _part_size_mm reads geometry
    instead of plate_size/motor_size_mm)."""
    ox, oy = offset
    u_min, u_max, v_min, v_max = view.u_min + ox, view.u_max + ox, view.v_min + oy, view.v_max + oy

    _draw_horizontal_dim_pdf(c, to_page, u_min, u_max, v_min, v_min - 16, f"{view.width:.1f}")
    _draw_vertical_dim_pdf(c, to_page, v_min, v_max, u_min, u_min - 10, f"{view.height:.1f}")

    for cx, cy, r in _distinct_hole_callouts(_detect_circles(view)):
        _draw_diameter_leader_pdf(c, to_page, cx + ox, cy + oy, r, f"\u2300{2 * r:.1f}")


def _draw_view_pdf(c, view: _View, offset: tuple[float, float], to_page) -> None:
    ox, oy = offset
    for line in view.visible:
        pts = [to_page((x + ox, y + oy)) for x, y in line]
        _draw_open_polyline_pdf(c, pts, dashed=False)
    for line in view.hidden:
        pts = [to_page((x + ox, y + oy)) for x, y in line]
        _draw_open_polyline_pdf(c, pts, dashed=True)
    label_pt = to_page((view.u_min + ox, view.v_min + oy - 6))
    c.setFont("Helvetica-Bold", 8)
    c.drawString(label_pt[0], label_pt[1], view.label)


def export_pdf(
    obj: ShapeLike,
    path: Path,
    part_name: str = "PART",
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> Path:
    """Multi-view orthographic PDF (front/top/side, HLR visible/hidden
    edges, title block), at true 1:1 scale. If `parts` is given (assembly
    sub-parts, see assembly.get_assembly_parts), draws one such block per
    part, stacked on one sheet, instead of a single block for `obj`."""
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    if parts:
        blocks = _stack_part_blocks(parts)
        all_offsets = [
            {name: (o[0], o[1] + y_shift) for name, o in offsets.items()}
            for _, _, offsets, y_shift in blocks
        ]
        overall_x0 = overall_y0 = float("inf")
        overall_x1 = overall_y1 = float("-inf")
        for (_, views, _, _), offsets in zip(blocks, all_offsets):
            x0, x1, y0, y1 = _combined_bbox(views, offsets, label_clearance=20.0, left_clearance=14.0)
            overall_x0, overall_x1 = min(overall_x0, x0), max(overall_x1, x1)
            overall_y0, overall_y1 = min(overall_y0, y0), max(overall_y1, y1)
        part_size_mm = None  # sheet holds multiple distinct parts - no single (X,Y,Z) to report
    else:
        views = _build_three_views(_as_workplane(obj))
        offsets = _layout_three_views(views)
        blocks = [(part_name, views, offsets, 0.0)]
        all_offsets = [offsets]
        overall_x0, overall_x1, overall_y0, overall_y1 = _combined_bbox(
            views, offsets, label_clearance=20.0, left_clearance=14.0
        )
        part_size_mm = _part_size_mm(views)

    drawing_w_mm = overall_x1 - overall_x0
    drawing_h_mm = overall_y1 - overall_y0

    margin = 20 * mm
    title_block_h = 28 * mm
    page_w = max(drawing_w_mm * mm + 2 * margin, 150 * mm)
    page_h = drawing_h_mm * mm + 2 * margin + title_block_h

    path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(path), pagesize=(page_w, page_h))

    origin_x = margin - overall_x0 * mm
    origin_y = margin + title_block_h - overall_y0 * mm

    def to_page(pt: tuple[float, float]) -> tuple[float, float]:
        return (origin_x + pt[0] * mm, origin_y + pt[1] * mm)

    # No longer load-bearing - _draw_open_polyline_pdf now sets its own
    # width on every call - but kept as the sane default for the title
    # block's own border/divider lines drawn further down, which don't
    # go through that helper.
    c.setLineWidth(_VISIBLE_LINE_WIDTH_MM * mm)
    c.setStrokeColorRGB(0, 0, 0)

    for (label, block_views, _, y_shift), offsets in zip(blocks, all_offsets):
        if parts:
            first = block_views[0]
            fx, fy = offsets["front"]
            label_pt = to_page((fx, fy + first.height + 12))
            c.setFont("Helvetica-Bold", 10)
            c.drawString(label_pt[0], label_pt[1], label.upper())
        for view in block_views:
            _draw_view_pdf(c, view, offsets[view.name], to_page)
            _add_dimensions_pdf(c, view, offsets[view.name], to_page)

    # Title block
    tb_x0, tb_y0 = margin, margin
    tb_w = page_w - 2 * margin
    c.rect(tb_x0, tb_y0, tb_w, title_block_h, stroke=1, fill=0)
    c.line(tb_x0, tb_y0 + title_block_h / 2, tb_x0 + tb_w, tb_y0 + title_block_h / 2)
    c.line(tb_x0 + tb_w * 0.38, tb_y0, tb_x0 + tb_w * 0.38, tb_y0 + title_block_h)
    c.line(tb_x0 + tb_w * 0.7, tb_y0, tb_x0 + tb_w * 0.7, tb_y0 + title_block_h)

    c.setFont("Helvetica-Bold", 10)
    c.drawString(tb_x0 + 5, tb_y0 + title_block_h - 14, f"PART: {part_name.upper()}")
    c.setFont("Helvetica", 8)
    c.drawString(tb_x0 + 5, tb_y0 + 8, f"TYPE: {(part_type or 'n/a').upper()}")
    c.drawString(tb_x0 + tb_w * 0.4, tb_y0 + title_block_h - 14, "SCALE: 1:1")
    # SIZE is the real (X, Y, Z) size of the solid, read back off the HLR
    # views (_part_size_mm) - NOT drawing_w_mm/drawing_h_mm, which is the
    # SHEET's layout extent (three tiled views + gaps + title block).
    # Reporting the sheet extent here was the original bug: a 97mm plate's
    # title block claimed "257.5 x 122.5mm" because that's how much page
    # space three views + dimensions took up, not the part's real size.
    if part_size_mm:
        size_text = f"SIZE: {part_size_mm[0]:.1f} x {part_size_mm[1]:.1f} x {part_size_mm[2]:.1f} mm"
    else:
        size_text = "SIZE: n/a (multi-part sheet)"
    c.drawString(tb_x0 + tb_w * 0.4, tb_y0 + 8, size_text)
    c.drawString(tb_x0 + tb_w * 0.72, tb_y0 + title_block_h - 14, f"MATERIAL: {material or 'n/a'}")
    c.drawString(tb_x0 + tb_w * 0.72, tb_y0 + 8, f"DATE: {_dt.date.today().isoformat()}")

    c.showPage()
    c.save()
    return path


# --------------------------------------------------------------------
# Orchestrator
# --------------------------------------------------------------------

def export_all(
    obj: ShapeLike,
    output_dir: Path,
    base_name: str,
    formats: list[str] | None = None,
    part_name: str | None = None,
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> dict[str, Path]:
    """Export `obj` to every format in `formats` (default: every format in
    DEFAULT_FORMATS - step, stl, iges, dxf, pdf). Returns
    {format: output_path}. Raises GenerationError on an unknown format or
    if any individual export fails - callers that want partial success on
    partial failure should call the individual export_* functions
    directly instead.

    `parts`: optional list of (name, shape) for assembly sub-parts (see
    assembly.get_assembly_parts). Only affects dxf/pdf, which draw one
    multi-view block per part instead of one block for `obj`. step/stl/
    iges are unaffected and still export `obj` as-is - STEP already
    preserves named sub-parts via Assembly.save() (see cad_generator.py),
    and STL/IGES don't have a per-part drawing concept.
    """
    resolved_formats = validate_formats(list(formats) if formats else list(DEFAULT_FORMATS))
    label = part_name or base_name

    results: dict[str, Path] = {}
    for fmt in resolved_formats:
        out_path = output_dir / f"{base_name}.{_EXTENSION_BY_FORMAT[fmt]}"
        try:
            if fmt == "step":
                export_step(obj, out_path)
            elif fmt == "stl":
                export_stl(obj, out_path)
            elif fmt == "iges":
                export_iges(obj, out_path)
            elif fmt == "dxf":
                export_dxf(obj, out_path, part_name=label, material=material, part_type=part_type, parts=parts)
            elif fmt == "pdf":
                export_pdf(obj, out_path, part_name=label, material=material, part_type=part_type, parts=parts)
        except GenerationError:
            raise
        except Exception as exc:  # noqa: BLE001 - cadquery/OCP/ezdxf/reportlab all raise different types
            raise GenerationError(f"{fmt.upper()} export failed: {exc}") from exc
        results[fmt] = out_path

    return results
